import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  rssform,
  contentlist,
}: Readonly<{
  children: React.ReactNode;
  rssform: React.ReactNode;
  contentlist: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full p-24 flex flex-wrap">
          <nav className="flex flex-col h-full w-[500px] flex-wrap items-center gap-16 p-24">
            {rssform}
            {contentlist}
          </nav>
          <section className="flex justify-center items-center max-w-[1000px]">
            {children}
          </section>
        </main>
      </body>
    </html>
  );
}
